version: '3'

services:
  php:
    image: supermp/php
    volumes:
      - app:/var/www/html

  nginx:
    image: nginx:1.18
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - app:/var/www/html

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  app:
  mysql:
